baseURL = 'https://jalbertcruz.github.io'
theme = 'ananke'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Personal blog'
    weight = 2

  [languages.en.params]
    subtitle = 'Reference, Tutorials, and Explanations'
  [languages.es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es'
    languageDirection = 'ltr'
    languageName = 'Spanish'
    title = 'Blog personal'
    weight = 1
    [languages.es.params]
      subtitle = 'Referencia, tutoriales y exposiciones'

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = ['asciidoctor-diagram']
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = true

    [markup.asciidocExt.attributes]
        source-highlighter = 'pygments'
        pygments-style = 'manni'
        
[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
